### ISSUE TITLE
Cannot access child value on Newtonsoft.Json.Linq.JValue

### ISSUE THREAD

**Issue by jcansdale** [grokys/Octokit.GraphQL#11]
The following fails with an exception:

```
var query = new Query().Repository("jcansdale", "TestDriven.Net-Issues").Issues(first: 60).Nodes.Select(
   i => new { i.Title, i.State, Milestone = i.Milestone.Title}).Where(i => i.Note != null);
```

```
	System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
	at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
	at lambda_method(Closure , JToken )
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
```

But this works:

```
var query = new Query().Repository("jcansdale", "TestDriven.Net-Issues").Issues(first: 60).Nodes.Select(
  i => new { i.Title, i.State, Milestone = i.Milestone.Select(m => m.Title)}).Where(i => i.Note != null);
```

**Comment by grokys** [comment]
This no longer compiles, as it's not possible to execute this type of `Where` statement in a GraphQL query.

**Comment by vstiara** [comment]
We should consider making this dynamic.
